-- Air quality data seed
-- Generated by dataset-analysis/scripts/build_air_quality_assets.py

DROP TABLE IF EXISTS public.environment_air_quality_stations;
CREATE TABLE public.environment_air_quality_stations (
    id SERIAL PRIMARY KEY,
    city text,
    district text,
    site_id integer,
    site_name text,
    status text,
    aqi double precision,
    pollutant text,
    so2_ppb double precision,
    co_ppm double precision,
    o3_ppb double precision,
    o3_8hr_ppb double precision,
    pm10_ug_m3 double precision,
    pm2_5_ug_m3 double precision,
    no2_ppb double precision,
    nox_ppb double precision,
    no_ppb double precision,
    wind_speed_m_sec double precision,
    wind_direction_degree double precision,
    co_8hr_ppm double precision,
    pm2_5_avg_ug_m3 double precision,
    pm10_avg_ug_m3 double precision,
    so2_avg_ppb double precision,
    longitude double precision,
    latitude double precision,
    publish_time text,
    import_date text,
    source_dataset text,
    updated_at text
);

DROP TABLE IF EXISTS public.environment_pressure_index;
CREATE TABLE public.environment_pressure_index (
    id SERIAL PRIMARY KEY,
    city text,
    district text,
    period text,
    pressure_type text,
    metric_name text,
    station_count integer,
    avg_aqi double precision,
    max_aqi double precision,
    avg_pm2_5 double precision,
    avg_pm10 double precision,
    avg_o3_8hr double precision,
    worst_status text,
    dominant_pollutant text,
    score double precision,
    unit text,
    source_dataset text,
    updated_at text
);

COPY public.environment_air_quality_stations (city, district, site_id, site_name, status, aqi, pollutant, so2_ppb, co_ppm, o3_ppb, o3_8hr_ppb, pm10_ug_m3, pm2_5_ug_m3, no2_ppb, nox_ppb, no_ppb, wind_speed_m_sec, wind_direction_degree, co_8hr_ppm, pm2_5_avg_ug_m3, pm10_avg_ug_m3, so2_avg_ppb, longitude, latitude, publish_time, import_date, source_dataset, updated_at) FROM stdin;
新北市	三重區	67	三重	普通	75	細懸浮微粒	0.5	0.41	8	4	19	9	10	13.3	2.4	\N	\N	0.9	21.3	32	0	121.4938	25.0726	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	三重區	8	菜寮	普通	75	細懸浮微粒	0.7	0.44	6	4	19	16	15	17.4	2.1	0.5	302	0.8	21.2	32	0	121.481	25.069	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	土城區	5	土城	普通	69	細懸浮微粒	0.6	0.42	2	8	36	13	13	15.1	1.7	0.3	142	0.4	19.2	36	0	121.4519	24.9825	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	新店區	4	新店	普通	54	細懸浮微粒	0.3	0.22	15	19	18	14	3	3.8	0.4	1.2	151	0.2	13.5	21	0	121.5378	24.9772	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	新莊區	7	新莊	普通	81	細懸浮微粒	0.3	0.53	3	5	42	28	16	17.9	1	0.6	262	0.6	23.3	41	0	121.4325	25.038	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	板橋區	6	板橋	普通	73	細懸浮微粒	1.1	0.48	4	9	28	21	14	15.6	1	0.2	269	0.5	20.5	33	1	121.4587	25.013	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	林口區	9	林口	普通	72	細懸浮微粒	2.4	0.4	29	27	30	22	11	11.9	0.5	0.4	152	0.4	20	32	1	121.3655	25.078	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	樹林區	311	新北（樹林）	普通	68	細懸浮微粒	0	0.27	6	11	31	16	5	6.7	1.1	0.2	92	0.3	18.6	29	1	121.3835	24.949	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	永和區	70	永和	普通	52	細懸浮微粒	0.7	0.25	13	13	19	9	3	5	1.3	1	133	0.4	12.9	23	1	121.5163	25.017	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	汐止區	2	汐止	普通	52	細懸浮微粒	1	0.35	4	5	19	11	11	13.3	2	0.4	126	0.4	13	24	1	121.6408	25.0662	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	淡水區	10	淡水	普通	72	細懸浮微粒	1.2	0.57	4	12	29	19	19	20.2	0.6	\N	\N	0.6	20	34	1	121.4492	25.1645	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	石門區	84	富貴角	普通	56	細懸浮微粒	0.7	0.28	31	36	27	13	5	5.3	0	1.2	234	0.2	14.5	27	0	121.5366	25.2968	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
臺北市	中山區	12	中山	普通	67	細懸浮微粒	0.5	0.28	14	12	23	15	7	8.5	0.6	0.9	208	0.5	18.3	30	0	121.5265	25.0624	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
臺北市	北投區	11	士林	普通	61	細懸浮微粒	0.8	0.36	9	17	21	14	9	10.2	1.1	0.4	18	0.4	16.1	26	1	121.5167	25.1033	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
臺北市	北投區	64	陽明	良好	44	\N	1.1	0.26	57	47	38	18	4	4.3	0.1	\N	\N	0.2	11	26	1	121.5296	25.1827	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
臺北市	大同區	16	大同	普通	73	細懸浮微粒	0.3	0.44	10	4	15	16	11	13.7	2.5	\N	\N	0.9	20.6	27	0	121.5134	25.0633	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
臺北市	大安區	14	古亭	普通	52	細懸浮微粒	1.1	0.25	13	17	20	16	5	6.5	0.7	0.8	154	0.3	12.9	24	1	121.5296	25.0206	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
臺北市	松山區	15	松山	良好	49	\N	0	0.33	13	12	20	11	10	13.5	2.9	0.4	194	0.4	12.2	24	2	121.5786	25.05	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
臺北市	萬華區	13	萬華	普通	60	細懸浮微粒	0.5	0.27	13	13	17	13	6	6.7	0.5	0.6	151	0.4	15.8	27	0	121.508	25.0465	2026/05/03 04:00:00	\N	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
\.

COPY public.environment_pressure_index (city, district, period, pressure_type, metric_name, station_count, avg_aqi, max_aqi, avg_pm2_5, avg_pm10, avg_o3_8hr, worst_status, dominant_pollutant, score, unit, source_dataset, updated_at) FROM stdin;
新北市	三重區	2026/05/03 04:00:00	空氣	AQI	2	75	75	21.25	32	4	普通	細懸浮微粒	75	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	土城區	2026/05/03 04:00:00	空氣	AQI	1	69	69	19.2	36	8	普通	細懸浮微粒	69	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	新店區	2026/05/03 04:00:00	空氣	AQI	1	54	54	13.5	21	19	普通	細懸浮微粒	54	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	新莊區	2026/05/03 04:00:00	空氣	AQI	1	81	81	23.3	41	5	普通	細懸浮微粒	81	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	板橋區	2026/05/03 04:00:00	空氣	AQI	1	73	73	20.5	33	9	普通	細懸浮微粒	73	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	林口區	2026/05/03 04:00:00	空氣	AQI	1	72	72	20	32	27	普通	細懸浮微粒	72	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	樹林區	2026/05/03 04:00:00	空氣	AQI	1	68	68	18.6	29	11	普通	細懸浮微粒	68	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	永和區	2026/05/03 04:00:00	空氣	AQI	1	52	52	12.9	23	13	普通	細懸浮微粒	52	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	汐止區	2026/05/03 04:00:00	空氣	AQI	1	52	52	13	24	5	普通	細懸浮微粒	52	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	淡水區	2026/05/03 04:00:00	空氣	AQI	1	72	72	20	34	12	普通	細懸浮微粒	72	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
新北市	石門區	2026/05/03 04:00:00	空氣	AQI	1	56	56	14.5	27	36	普通	細懸浮微粒	56	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
臺北市	中山區	2026/05/03 04:00:00	空氣	AQI	1	67	67	18.3	30	12	普通	細懸浮微粒	67	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
臺北市	北投區	2026/05/03 04:00:00	空氣	AQI	2	52.5	61	13.55	26	32	普通	細懸浮微粒	61	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
臺北市	大同區	2026/05/03 04:00:00	空氣	AQI	1	73	73	20.6	27	4	普通	細懸浮微粒	73	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
臺北市	大安區	2026/05/03 04:00:00	空氣	AQI	1	52	52	12.9	24	17	普通	細懸浮微粒	52	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
臺北市	松山區	2026/05/03 04:00:00	空氣	AQI	1	49	49	12.2	24	12	良好	\N	49	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
臺北市	萬華區	2026/05/03 04:00:00	空氣	AQI	1	60	60	15.8	27	13	普通	細懸浮微粒	60	score_0_100	MOENV AQX_P_432	2026-05-03T04:37:46+08:00
\.

CREATE INDEX IF NOT EXISTS environment_air_quality_stations_city_district_idx
ON public.environment_air_quality_stations (city, district);

CREATE INDEX IF NOT EXISTS environment_pressure_index_city_district_type_idx
ON public.environment_pressure_index (city, district, pressure_type);

SELECT pg_catalog.setval(
    'public.environment_air_quality_stations_id_seq',
    (SELECT COALESCE(MAX(id), 0) FROM public.environment_air_quality_stations),
    true
);

SELECT pg_catalog.setval(
    'public.environment_pressure_index_id_seq',
    (SELECT COALESCE(MAX(id), 0) FROM public.environment_pressure_index),
    true
);
