-- Air quality data seed
-- Generated by dataset-analysis/scripts/build_air_quality_assets.py

DROP TABLE IF EXISTS public.environment_air_quality_stations;
CREATE TABLE public.environment_air_quality_stations (
    id SERIAL PRIMARY KEY,
    city text,
    district text,
    site_id integer,
    site_name text,
    status text,
    aqi double precision,
    pollutant text,
    so2_ppb double precision,
    co_ppm double precision,
    o3_ppb double precision,
    o3_8hr_ppb double precision,
    pm10_ug_m3 double precision,
    pm2_5_ug_m3 double precision,
    no2_ppb double precision,
    nox_ppb double precision,
    no_ppb double precision,
    wind_speed_m_sec double precision,
    wind_direction_degree double precision,
    co_8hr_ppm double precision,
    pm2_5_avg_ug_m3 double precision,
    pm10_avg_ug_m3 double precision,
    so2_avg_ppb double precision,
    longitude double precision,
    latitude double precision,
    publish_time text,
    import_date text,
    source_dataset text,
    updated_at text
);

DROP TABLE IF EXISTS public.environment_pressure_index;
CREATE TABLE public.environment_pressure_index (
    id SERIAL PRIMARY KEY,
    city text,
    district text,
    period text,
    pressure_type text,
    metric_name text,
    station_count integer,
    avg_aqi double precision,
    max_aqi double precision,
    avg_pm2_5 double precision,
    avg_pm10 double precision,
    avg_o3_8hr double precision,
    worst_status text,
    dominant_pollutant text,
    score double precision,
    unit text,
    source_dataset text,
    updated_at text
);

COPY public.environment_air_quality_stations (city, district, site_id, site_name, status, aqi, pollutant, so2_ppb, co_ppm, o3_ppb, o3_8hr_ppb, pm10_ug_m3, pm2_5_ug_m3, no2_ppb, nox_ppb, no_ppb, wind_speed_m_sec, wind_direction_degree, co_8hr_ppm, pm2_5_avg_ug_m3, pm10_avg_ug_m3, so2_avg_ppb, longitude, latitude, publish_time, import_date, source_dataset, updated_at) FROM stdin;
新北市	三重區	67	三重	普通	77	細懸浮微粒	1.1	1.08	4	16	23	17	32	71.9	39.2	\N	\N	1	22	37	0	121.4938	25.0726	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	三重區	8	菜寮	普通	74	細懸浮微粒	0.6	0.95	2	29	37	23	41	49.7	8.4	0.6	216	0.7	20.8	38	0	121.481	25.069	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	土城區	5	土城	普通	71	細懸浮微粒	0.9	0.53	7	32	34	22	21	23.9	2	0.3	152	0.4	19.7	37	0	121.4519	24.9825	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	新店區	4	新店	普通	59	細懸浮微粒	0.5	0.3	20	39	18	17	8	9.7	0.8	0.5	180	0.3	15.3	24	0	121.5378	24.9772	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	新莊區	7	新莊	普通	73	細懸浮微粒	0.8	0.68	8	30	38	16	23	24.1	0.2	0.8	228	0.5	20.5	46	0	121.4325	25.038	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	板橋區	6	板橋	普通	71	細懸浮微粒	0.8	0.75	4	35	40	28	29	32.4	3.2	0.7	237	0.5	19.9	34	1	121.4587	25.013	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	林口區	9	林口	普通	73	細懸浮微粒	1.5	0.45	23	36	32	19	19	20.7	1.1	0.3	247	0.5	20.7	35	1	121.3655	25.078	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	樹林區	311	新北（樹林）	普通	73	細懸浮微粒	1	0.41	12	36	36	18	12	14.7	2.6	0.5	90	0.4	20.4	33	1	121.3835	24.949	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	永和區	70	永和	普通	61	細懸浮微粒	1	0.62	12	31	27	16	16	20.6	4.3	0.9	142	0.6	16	32	1	121.5163	25.017	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	汐止區	2	汐止	普通	61	細懸浮微粒	1.3	0.55	1	28	35	15	26	34.9	8.2	0.4	117	0.5	16.3	28	1	121.6408	25.0662	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	淡水區	10	淡水	普通	76	細懸浮微粒	1.1	0.67	13	40	40	21	23	24.7	1.4	\N	\N	0.4	21.5	39	0	121.4492	25.1645	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	石門區	84	富貴角	普通	58	臭氧八小時	0.6	0.2	53	57	23	12	4	4	0	1.2	225	0.1	13.7	27	0	121.5366	25.2968	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
臺北市	中山區	12	中山	普通	77	細懸浮微粒	0.8	0.63	12	30	32	19	28	33	4.1	1	172	0.5	22.1	37	0	121.5265	25.0624	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
臺北市	北投區	11	士林	普通	66	細懸浮微粒	1.2	0.56	14	35	32	22	22	22.8	0.2	0.4	132	0.4	18	33	1	121.5167	25.1033	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
臺北市	北投區	64	陽明	良好	45	\N	1.3	0.22	45	49	16	9	3	3.4	0.4	\N	\N	0.2	10	22	1	121.5296	25.1827	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
臺北市	大同區	16	大同	普通	75	細懸浮微粒	0.8	1.28	3	18	23	17	37	62.5	24.9	\N	\N	0.9	21.1	33	0	121.5134	25.0633	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
臺北市	大安區	14	古亭	普通	59	細懸浮微粒	1.1	0.4	19	35	21	13	15	16.7	0.9	1.3	127	0.4	15.4	30	1	121.5296	25.0206	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
臺北市	松山區	15	松山	普通	60	細懸浮微粒	1.7	0.54	7	29	23	11	25	28.5	3	0.4	42	0.4	15.7	31	2	121.5786	25.05	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
臺北市	萬華區	13	萬華	普通	66	細懸浮微粒	0.7	0.47	15	34	21	12	18	19.1	0.7	0.9	164	0.4	18	31	0	121.508	25.0465	2026/05/02 23:00:00	\N	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
\.

COPY public.environment_pressure_index (city, district, period, pressure_type, metric_name, station_count, avg_aqi, max_aqi, avg_pm2_5, avg_pm10, avg_o3_8hr, worst_status, dominant_pollutant, score, unit, source_dataset, updated_at) FROM stdin;
新北市	三重區	2026/05/02 23:00:00	空氣	AQI	2	75.5	77	21.4	37.5	22.5	普通	細懸浮微粒	77	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	土城區	2026/05/02 23:00:00	空氣	AQI	1	71	71	19.7	37	32	普通	細懸浮微粒	71	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	新店區	2026/05/02 23:00:00	空氣	AQI	1	59	59	15.3	24	39	普通	細懸浮微粒	59	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	新莊區	2026/05/02 23:00:00	空氣	AQI	1	73	73	20.5	46	30	普通	細懸浮微粒	73	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	板橋區	2026/05/02 23:00:00	空氣	AQI	1	71	71	19.9	34	35	普通	細懸浮微粒	71	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	林口區	2026/05/02 23:00:00	空氣	AQI	1	73	73	20.7	35	36	普通	細懸浮微粒	73	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	樹林區	2026/05/02 23:00:00	空氣	AQI	1	73	73	20.4	33	36	普通	細懸浮微粒	73	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	永和區	2026/05/02 23:00:00	空氣	AQI	1	61	61	16	32	31	普通	細懸浮微粒	61	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	汐止區	2026/05/02 23:00:00	空氣	AQI	1	61	61	16.3	28	28	普通	細懸浮微粒	61	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	淡水區	2026/05/02 23:00:00	空氣	AQI	1	76	76	21.5	39	40	普通	細懸浮微粒	76	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
新北市	石門區	2026/05/02 23:00:00	空氣	AQI	1	58	58	13.7	27	57	普通	臭氧八小時	58	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
臺北市	中山區	2026/05/02 23:00:00	空氣	AQI	1	77	77	22.1	37	30	普通	細懸浮微粒	77	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
臺北市	北投區	2026/05/02 23:00:00	空氣	AQI	2	55.5	66	14	27.5	42	普通	細懸浮微粒	66	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
臺北市	大同區	2026/05/02 23:00:00	空氣	AQI	1	75	75	21.1	33	18	普通	細懸浮微粒	75	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
臺北市	大安區	2026/05/02 23:00:00	空氣	AQI	1	59	59	15.4	30	35	普通	細懸浮微粒	59	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
臺北市	松山區	2026/05/02 23:00:00	空氣	AQI	1	60	60	15.7	31	29	普通	細懸浮微粒	60	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
臺北市	萬華區	2026/05/02 23:00:00	空氣	AQI	1	66	66	18	31	34	普通	細懸浮微粒	66	score_0_100	MOENV AQX_P_432	2026-05-02T23:54:41+08:00
\.

CREATE INDEX IF NOT EXISTS environment_air_quality_stations_city_district_idx
ON public.environment_air_quality_stations (city, district);

CREATE INDEX IF NOT EXISTS environment_pressure_index_city_district_type_idx
ON public.environment_pressure_index (city, district, pressure_type);

SELECT pg_catalog.setval(
    'public.environment_air_quality_stations_id_seq',
    (SELECT COALESCE(MAX(id), 0) FROM public.environment_air_quality_stations),
    true
);

SELECT pg_catalog.setval(
    'public.environment_pressure_index_id_seq',
    (SELECT COALESCE(MAX(id), 0) FROM public.environment_pressure_index),
    true
);
